name: trace
description: Trace is a minimalistic logger for your Dart & Flutter projects, that uses AnsiX to print customizable messages in terminal and export log files.
version: 0.0.8-prerelease

homepage: https://github.com/nikosportolos/trace
repository: https://github.com/nikosportolos/trace
documentation: https://github.com/nikosportolos/trace
issue_tracker: https://github.com/nikosportolos/trace/issues

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  ansix: ^0.3.5
  collection: ^1.19.0
  data_class_plugin: ^1.5.3
  date_time_format: ^2.0.1
  meta: ^1.17.0
  path: ^1.9.0
  rxdart: ^0.28.0
  stack_trace: ^1.12.1

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  tachyon: ^0.3.2
  test: ^1.26.3

screenshots:
  - description: 'This is a sample usage of Trace using ConsoleLogger'
    path: assets/images/examples.png
  - description: 'This is a sample usage of Trace using FileLogger'
    path: assets/images/file-example.png
  - description: 'This is a sample usage of Trace on a web app'
    path: assets/images/web-example.png
  - description: 'This is a sample usage of a bulleted list'
    path: assets/images/list-example.png

topics:
  - trace
  - log
  - print
  - console
  - file
